### ISSUE TITLE
missing repo_repoman", package_version="0.1.1-beta2",

### ISSUE THREAD

**Issue by amor212** [gazebosim/gz-omni#31]
Starting >>> ignition-omniverse1
--- stderr: ignition-omniverse1                               
Traceback (most recent call last):
  File "./tools/repoman/build.py", line 5, in <module>
    import repoman
  File "/home/amer/ign-omni/src/ign-omni/tools/repoman/repoman.py", line 12, in <module>
    packmanapi.install("repo_repoman", package_version="0.1.1-beta2", link_path=repoman_link_path)
  File "/home/amer/packman-repo/packman-common/6.32/utils.py", line 478, in wrapper_message_block
    return func(*args, **kwargs)
  File "/home/amer/packman-repo/packman-common/6.32/packman.py", line 526, in install
    name, package_version, postscript, remotes, project_path, link_path, cache_expiration, None
  File "/home/amer/packman-repo/packman-common/6.32/packman.py", line 499, in install_with_variable_file
    args=args,
  File "/home/amer/packman-repo/packman-common/6.32/packman.py", line 1360, in pull_dependencies
    package_path, target_filename
  File "/home/amer/packman-repo/packman-common/6.32/transport/httptransport.py", line 102, in download_file
    "Unable to download file from '%s' (server returned %s)" % (url, r.status_code)
errors.PackmanError: Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/repo_repoman%400.1.1-beta2' (server returned 403)
gmake[2]: *** [CMakeFiles/build.dir/build.make:70: CMakeFiles/build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/build.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
---
Failed   <<< ignition-omniverse1 [3.11s, exited with code 2]

Summary: 9 packages finished [1min 9s]
  1 package failed: ignition-omniverse1

**Comment by amor212** [comment]
i am running the code on ubuntu 22.04, ROS2 humble, Gazebo Fortress 
i cant build the package because repo_repoman", package_version="0.1.1-beta2", cannot be downloaded from the provided link 
is there anyway to get it from another link ?
